### PR TITLE
add kbd for magit-log-select-mode

### PR DESCRIPTION
**Pull request by tshu-w**
before:
Screen Shot 2021-01-15 at 2 24 22 PM
after:
Screen Shot 2021-01-15 at 2 23 21 PM

BTW, I'm not quite sure whether we should use `p` or `RET` to `magit-log-select-pick`

### CODE REVIEW

**Comment by jojojames** [comment]
What does magit-log-select-pick do? I'm guessing from the name RET would be appropriate.

**Comment by tshu-w** [comment]
> What does magit-log-select-pick do? I'm guessing from the name RET would be appropriate.

For example, if I want to modify a commit, I can type `r`(rebase) `m`(modify a commit) and move the cursor to the commit I want to select, and then run `magit-log-select-pick`

**Comment by condy0919** [comment]
If I remember correct, the default binding is <kbd>C-c C-c</kbd> to
fixup, <kbd>C-c C-k</kbd> to abort

**Comment by tshu-w** [comment]
> If I remember correct, the default binding is C-c C-c to
> fixup, C-c C-k to abort

Yes, but also `e` and `q` if I don't use evil-collection. evil-collection change `magit-log-select-mode ` init mode to normal and somehow make `magit-log-select-quit` shortcut hint to stop appearing.

**Comment by jojojames** [comment]
> evil-collection change magit-log-select-mode init mode to normal

Do you remember if that was true for evil-magit as well? Maybe there was a bug during the transition.

**Comment by tshu-w** [comment]
@jojojames I don't really remember, I used to use spacemacs and had its own set of settings. But now I have the same problem with evil-magit.

**Comment by tshu-w** [comment]
I close this pull request and create issue #444, once that was confirmed, I was happy to submit another pull request.

**Comment by tshu-w** [comment]
> If I remember correct, the default binding is C-c C-c to
> fixup, C-c C-k to abort

You are right, default binding was not shown because of sis https://github.com/laishulu/emacs-smart-input-source/issues/28, so shall we configure more convenient kbd?

**Pull request closed without merging**
