### PR TITLE
apropos-mode: binds <tab>/<backtab> to forward/backward-button

### PR DESCRIPTION
**Pull request by kiennq**

### CODE REVIEW

**Comment by Ambrevar** [comment]
Thanks for the catch!
Can you use the `(kbd "TAB")` and `(kbd "S-TAB")` syntax?

**Comment by kiennq** [comment]
Fixed

**Comment by kiennq** [comment]
Friendly ping

**Comment by jojojames** [comment]
Looks good to me and thanks for the ping. :D

**Pull request merged**
