### PR TITLE
bookmark: {mark,unmark}-all

### PR DESCRIPTION
**Pull request by condy0919**
Put `global-evil-collection-unimpaired-mode` into a group to make CI happy

### CODE REVIEW

**Comment by Ambrevar** [comment]
Looking good, but can you make 2 separate commits and explain in the commit message about unimpaired mode why we need this?

**Comment by condy0919** [comment]
done :-)

**Comment by Ambrevar** [comment]
Tip: You could have pushed directly here, it would have worked ;)
Thanks!

**Comment by condy0919** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thanks for the tip.                                                                                                                                                                                                                                                                                                                 From: notifications@github.comSent: October 21, 2020 23:33To: evil-collection@noreply.github.comReply-to: reply@reply.github.comCc: condy0919@gmail.com; author@noreply.github.comSubject: Re: [emacs-evil/evil-collection] bookmark: {mark,unmark}-all (#394)  
Tip: You could have pushed directly here, it would have worked ;)
Thanks!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request merged**
