### PR TITLE
Bind eshell-kill-input in Evil insert state

### PR DESCRIPTION
**Pull request by leungbk**
----

#

### CODE REVIEW

**Comment by Ambrevar** [comment]
Looks good to me, but I'm not familiar with these bindings.  @jojojames ?

**Comment by leungbk** [comment]
In terminals, C-u is commonly understood to delete text backwards until
reaching the beginning of the shell prompt. I assume that this influenced
Vi's choice of bindings here (or vice-versa). Vanilla Emacs also has C-c
C-u in Eshell as a default binding to backward-kill the prompt.

**Comment by leungbk** [comment]
Should we go ahead and change https://github.com/emacs-evil/evil-collection/blob/c68aed6a9694836602ada224160bc5b4c0a37919/modes/eshell/evil-collection-eshell.el#L82? Even if we don't really use `_beg`, the `evil-define-operator` macro expands to something that has to access `_beg` for bookkeeping purposes.

**Comment by Ambrevar** [comment]
Brian Leung <notifications@github.com> writes:

> In terminals, C-u is commonly understood to delete text backwards until
> reaching the beginning of the shell prompt. I assume that this influenced
> Vi's choice of bindings here (or vice-versa). Vanilla Emacs also has C-c
> C-u in Eshell as a default binding to backward-kill the prompt.

Makes sense, thanks for the explanation.

**Comment by Ambrevar** [comment]
> Should we go ahead and change https://github.com/emacs-evil/evil-collection/blob/c68aed6a9694836602ada224160bc5b4c0a37919/modes/eshell/evil-collection-eshell.el#L82? Even if we don't really use `_beg`, the `evil-define-operator` macro expands to something that has to access `_beg` for bookkeeping purposes.

To clarify, this is not related to your patch, or is it?

**Comment by leungbk** [comment]
> Should we go ahead and change https://github.com/emacs-evil/evil-collection/blob/c68aed6a9694836602ada224160bc5b4c0a37919/modes/eshell/evil-collection-eshell.el#L82? Even if we don't really use `_beg`, the `evil-define-operator` macro expands to something that has to access `_beg` for bookkeeping purposes.
> To clarify, this is not related to your patch, or is it?

It's not, it seems to have been introduced when the `doom`-inspired `eshell` functions were. The CI complaint is that `evil-define-operator` does use `_beg`, even though it winds up playing no role in any meaningful computations.

**Comment by jojojames** [comment]
> It's not, it seems to have been introduced when the doom-inspired eshell functions were. The CI complaint is that evil-define-operator does use _beg, even though it winds up playing no role in any meaningful computations.

Suggestion?

Otherwise, seems fine to merge.

**Comment by leungbk** [comment]
@jojojames I fixed the CI failure with a follow-up commit, so everything should be OK.

**Pull request merged**
