### PR TITLE
Continue of #720: Adapt evil-collection-mu4e for latest mu4e development version

### PR DESCRIPTION
**Pull request by milanglacier**
This is the continue of #720 since we want to resolve the byte compiler error.
And I would like to open a new PR at here such that I can directly test if the new commits resolve the byte compiler error.

### CODE REVIEW

**Comment by milanglacier** [comment]
> Does this PR superset the other one?

Previous PR was opened by @meliache, and I make contributions via firstly opening pull requests on his fork and then upon his approval will #720 get updated.

Since we are now focusing on fixing the byte compiler errors. I think it would be better that I directly open pull request at here to simplify the whole process

**Comment by milanglacier** [comment]
I didn't follow @meliache's way to fix the byte compiler error. Instead I took my own approach.
So #720 has 4 commits that does not in here: from 2a77375 to 095f8f1.

And this PR contains three commits that are not part of #720: `73c6370` to `1de1778`

**Comment by japhir** [comment]
I've just locally replaced my `modes/mu4e/evil-collection-mu4e.el` file with yours and removed the `.elc` file. It works on my machine (I'm on the newest mu)! I don't know anything about how you handle the older version and byte compilation though ;-).

**Comment by milanglacier** [comment]
Yes, the code for working on mu 1.10 but non-backward-compatible has been ready for a long while. The problem now is some of us want to keep backward compatibility and the #720 was once stale. 

I started to write the code for backward compatibility and want to make #720 merged ASAP and now what this PR current at is to fix the CI byte compiler error (the code works fine on my machine for both mu1.8 and mu1.10 though).

If we are keeping stale at the status of current progress, we may even no longer need this PR when mu 1.12 is out

**Comment by japhir** [comment]
I think this isn't getting merged yet because, as a bystander, I didn't see a clear answer to this question:
> Does this PR superset the other one?

Should @jojojames merge this pull request and close the other one and would that be to everyone's satisfaction?

**Comment by jojojames** [comment]
> Should @jojojames merge this pull request and close the other one (does it supersede the https://github.com/emacs-evil/evil-collection/pull/720?) and would that be to everyone's satisfaction?

Yeah, that is my question.

**Comment by milanglacier** [comment]
> > Should @jojojames merge this pull request and close the other one (does it supersede the #720?) and would that be to everyone's satisfaction?
> 
> Yeah, that is my question.

can we approve the work flow for and run the github CI to see if this patch fixes the byte compiler error?

#720 has been stale for a long time, and the byte compiler error **is not fixed**. I submitted my PR to the fork of 720 and it hasn’t being merged for a long time, that’s the reason **why I created a new patch here**.

**Comment by milanglacier** [comment]
> > Should @jojojames merge this pull request and close the other one (does it supersede the #720?) and would that be to everyone's satisfaction?
> 
> Yeah, that is my question.

Since #720 has been stale for a long time and it is me to start to write the backward compatibility code, I would say yes, we can start with this PR to supersede #720.

**Comment by japhir** [comment]
Does @meliache agree with the above? :)

Anyhow, tagging @jojojames again so he can approve the workflow 👍🏽

**Comment by milanglacier** [comment]
The byte compiler error has been fixed. Let me know if we have any questions for the patch to be merged!

**Comment by meliache** [comment]
Sorry I was a bit busy privately but this looks good to me!

**Pull request merged**
