### PR TITLE
TAB can move the point to the next link

### PR DESCRIPTION
**Pull request by condy0919**
The bindings are stolen from `evil-collection-man.el`

### CODE REVIEW

**Comment by Ambrevar** [comment]
This already works for me when the point is on links.
Maybe your local configuration is overriding these bindings?

**Comment by condy0919** [comment]
> This already works for me when the point is on links.
> Maybe your local configuration is overriding these bindings?

TAB on links runs `shr-next-link`. `forward-button` is more general, it can move the point to the next link even if the point is at plain text.

**Comment by Ambrevar** [comment]
Are you sure?  When I apply your patch and press "TAB", it echoes "No
buttons!"

But I noticed that in Emacs state, TAB is bound to
elfeed-show-next-link, which does what you want.

**Comment by condy0919** [comment]
Bind TAB to `elfeed-show-next-link` now.

**Comment by Ambrevar** [comment]
Can you squash the commits?  Thanks!

**Comment by condy0919** [comment]
Squashed!

**Comment by Ambrevar** [comment]
Sorry for being picky here :p  Could you prefix your commit message with the package you are targeting?
Here, it would be

```
elfeed: Bind TAB to move the point to the next link
```

Thank you for your patience :)

**Comment by condy0919** [comment]
Fixed

**Comment by Ambrevar** [comment]
Thanks a lot!

**Pull request merged**
