### PR TITLE
read-only mode bindings

### PR DESCRIPTION
**Pull request by condy0919**
Follow guides in #397 

There are tons of bindings to be refined though.

### CODE REVIEW

**Comment by condy0919** [comment]
@Ambrevar @MorganJamesSmith

**Comment by MorganJamesSmith** [comment]
I don't think you should remap `evil-record-macro`. The idea here is to make `q` quit, not overwrite `evil-record-macro`. However, if we just do an `evil-collection-define-key` for `q` then we have to make sure to call `evil-collection-set-readonly-bindings` before we setup any other bindings or else the readonly bindings will end up on top.

Is there a way to make the readonly bindings a proper keymap that can sit under a keymap? Can you retroactively decide inheritance?

I'm probably not qualified to review pull requests yet. Emacs is still very mysterious to me :P

**Comment by condy0919** [comment]
`evil-record-macro` is bound to `q` in defaults, using `[remap evil-record-macro]` is intended to keep consistent with other remaps. I don't think anyone could bind `evil-record-macro` to other keys, so it's acceptable.

Aftering looking through https://www.masteringemacs.org/article/mastering-key-bindings-emacs, `minor-mode-overriding-map-alist` is a choice.

@Ambrevar Any thoughts?

**Comment by jojojames** [comment]
I'd prefer the list of bindings/modes to be changed to be in the same CL so we can see what the blast radius of this change is. If it's actually really small, it'd beg the question whether we need this convenience function also.

The remap on record-macro seems spotty to me (I could definitely be convinced otherwise), if we make the assumption that most people's record-macro is on q, it seems it'd be easier to just make the assumption it's safe to rebind q and avoid any subtle break when someone does rebind record-macro. Just my quick knee-jerk reaction though.

**Comment by condy0919** [comment]
Can `evil-quit` be replaced with `quit-window`?
@jojojames @Ambrevar

**Comment by Ambrevar** [comment]
I agree with `quit-window`.  In fact it's what we are using in most of the code, but with some inconsistencies.

For instance hackernews and youtube-dl both bind ZZ to evil-quit.

I suggest the following rational update:

- Bind `q` to the mode specific quitting function, `quit-window` if there is none.
- Bind `ZZ` to `quit-window`.
- Bind `ZQ` to `evil-quit`.

Thoughts?

**Comment by condy0919** [comment]
> * Bind `q` to the mode specific quitting function, `quit-window` if there is none.
> * Bind `ZZ` to `quit-window`.
> * Bind `ZQ` to `evil-quit`.

Do agree.

**Comment by condy0919** [comment]
@jojojames @Ambrevar 

Most of modes are refined.

**Comment by MorganJamesSmith** [comment]
I still think it's worth pointing out that `evil-collection-set-readonly-bindings` should be called before setting up other keybinds so that it can be overriden. Adding this information to the docstring would make me happy

**Comment by Ambrevar** [comment]
Can you also update the README rationale?

**Comment by condy0919** [comment]
> I still think it's worth pointing out that `evil-collection-set-readonly-bindings` should be called before setting up other keybinds so that it can be overriden. Adding this information to the docstring would make me happy

Mentioned.

**Comment by condy0919** [comment]
> Can you also update the README rationale?

Updated.

**Comment by Ambrevar** [comment]
Excellent, thanks!

**Pull request merged**
