### PR TITLE
Update notmuch binds to reflect changes in notmuch

### PR DESCRIPTION
**Pull request by meain**
I was able to track this change to commit [adfded9ed0a5a4b06886f462314cd4511cb72d47](https://git.notmuchmail.org/git?p=notmuch;a=commit;h=adfded9ed0a5a4b06886f462314cd4511cb72d47).

I am kinda new to elisp, let me know if there are any issues.
Fixes https://github.com/emacs-evil/evil-collection/issues/415

### CODE REVIEW

**Review by ZenTauro — APPROVED** [review]
Just tried it, works again with the new version of notmuch

**Comment by firmart** [comment]
Thank you for the PR. 
- Looks like the CI doesn't recognize the (new?) function `notmuch-tree-help` or more generally `notmuch-tree-*` functions.
- I didn't try, but I following the documentation of `notmuch-tree-*` function you add, it seems that they already do what it supposes to do *i.e.* close pane. So I guess we don't have to rely on the internal function `notmuch-tree--define-close-message-window-and`. Simply bind the `notmuch-tree-*` function may do the job (and remove the `declare-function` part).

**Comment by jojojames** [comment]
You will want to address the compile error here.

```In toplevel form:

modes/notmuch/evil-collection-notmuch.el:172:57:Error: reference to free variable ‘notmuch-tree-help’

make: *** [compile] Error 1

The command "make compile" exited with 2.```

**Comment by meain** [comment]
@firmart Thank you for the guidance, will check on those.
@jojojames Will take a look into what the issue is.

**Comment by meain** [comment]
Also found that [`notmuch-hello-versions`](https://github.com/emacs-evil/evil-collection/pull/417/files#diff-24c79c4e508c8f2aa184f2a9d84f1e5799891f44d2f5ac01e0193a4c2473b020R127) does not exist in `notmuch` anymore and have fixed that.

**Comment by Ambrevar** [comment]
OK to merge then?

**Comment by meain** [comment]
Good to go from my end. Been using it for a while now and seems to be working fine so far.

**Comment by Ambrevar** [comment]
@jojojames Feel free to merge! :)

**Comment by jojojames** [comment]
Thanks!

**Pull request merged**
