### PR TITLE
rg: add evil bindings

### PR DESCRIPTION
**Pull request by condy0919**
`i` is bound to `rg-rerun-toggle-ignore` meanwhile `I` is bound to `wgrep-change-to-wgrep-mode`.

Should I swap the bindings?

### CODE REVIEW

**Comment by jojojames** [comment]
Yeah.

**Comment by condy0919** [comment]
> Yeah.

done

**Comment by condy0919** [comment]
@Ambrevar @jojojames Anything should I modify?

**Comment by jojojames** [comment]
Thanks!

**Pull request merged**
