### PR TITLE
Adds goto next and previous flymake bindings

### PR DESCRIPTION
**Pull request by jgarte**
WIP: I haven't tested these yet.

Testing help appreciated.

### CODE REVIEW

**Comment by condy0919** [comment]
If you use `unimpaired`, it can be done via `[l` and `]l`

**Comment by jgarte** [comment]
> If you use `unimpaired`, it can be done via `[l` and `]l`

@condy0919 You mean this package? 

https://github.com/zmaas/evil-unimpaired

**Comment by condy0919** [comment]
> > If you use `unimpaired`, it can be done via `[l` and `]l`
> 
> @condy0919 You mean this package?
> 
> https://github.com/zmaas/evil-unimpaired

https://github.com/emacs-evil/evil-collection/blob/master/modes/unimpaired/evil-collection-unimpaired.el#L240-L241

No, it's bundled with evil-collection.

**Comment by jojojames** [comment]
C-j and C-k seem like they'll clash with a lot of common binds since flymake is a more "global" minor mode during editing, imo.

**Comment by condy0919** [comment]
> C-j and C-k seem like they'll clash with a lot of common binds since flymake is a more "global" minor mode during editing, imo.

It defined keys in the diagnostic buffer.

**Pull request merged**
