### PR TITLE
Convert evil-collection-inhibit-insert-state to function

### PR DESCRIPTION
**Pull request by justbur**
Move to evil-collection.el. Make requires consistent across all package
files. Delete evil-collection-util.el.

This might be a little controversial, but I think these changes make things more consistent with respect to uses of require and the binding functions. Deleting evil-collection-util.el was a judgement call. I prefer it next to the main binding function, and the extra file with one function made it easy to forget to require that file.

### CODE REVIEW

**Comment by Ambrevar** [comment]
Agreed.  I'm Ok to merge this.
@jojojames?

**Comment by jojojames** [comment]
Fine by me, might be worth looking at the search util file too.

**Comment by Ambrevar** [comment]
@justbur Want to move `evil-collection-search-util.el` as well?

**Comment by justbur** [comment]
@Ambrevar I'm not sure what you mean

**Comment by Ambrevar** [comment]
What @jojojames suggest, add another commit to move the function from `evil-collection-search-util.el` to `evil-collection.el`. 

But no worries, I can also do it later.

**Comment by justbur** [comment]
I see. Sure, I just did it

**Pull request merged**
