### PR TITLE
Lint/remove dot

### PR DESCRIPTION
**Pull request by kiennq**
This fix linting errors so we have a clean build.

### CODE REVIEW

**Comment by Ambrevar** [comment]
See #323 about apropos.
Otherwise looks good to me.  @jojojames ?

**Comment by kiennq** [comment]
Ah, sorry I forgot to remove the previous commit out of this branch

**Comment by jojojames** [comment]
Looks good to me. Was the issue about apropos resolved? @kiennq 

Thanks for doing this! Awesome work :D

**Comment by kiennq** [comment]
> Looks good to me. Was the issue about apropos resolved?

@jojojames It should be resolved. In another PR though.

**Comment by jojojames** [comment]
Sounds good, thanks.

**Pull request merged**
