### PR TITLE
Ediff: Merge from evil-ediff.el

### PR DESCRIPTION
**Pull request by justbur**
Adds evil-collection-ediff.el

Ref #129 

Please check to make sure I followed the conventions of the repo properly.

### CODE REVIEW

**Comment by jojojames** [comment]
This looks good other than potentially the motion vs normal state default.

Ok to merge for me. @Ambrevar ?

**Comment by Ambrevar** [comment]
Should we change to normal state now or after the merge?
Switching to normal state can be tricky sometimes since many keys don't fallback to their Emacs-state equivalent the same way motion-state does.

**Comment by justbur** [comment]
What is the issue with motion state? I think motion state makes sense in buffers that are not intended to be edited, like the ediff control buffer.

**Comment by jojojames** [comment]
https://github.com/emacs-evil/evil-collection/issues/21

I think we reached a consensus to use normal state by default.

**Comment by justbur** [comment]
I just skimmed that thread. If normal state is the default, then that's what it should be. I don't think it will have a big effect here.

**Comment by noctuid** [comment]
Since that discussion was pretty long, it may make sense to summarize the reasoning somewhere. To summarize my points from that discussion, motion state is:
- confusing to many users (new users and users coming from vim; e.g. many users don't know when they should use the motion keymap and just bind their keys in normal, visual, and motion state, don't know about motion state and don't understand why their normal state keybindings don't work in buffers that start in motion state, etc.)
- poorly named (doesn't only contain motions)
- an incomplete solution to a minor issue that unnecessarily complicates things

I personally haven't had issues with accidental keypresses, but motion doesn't solve this issue for all non-editable buffers anyway (e.g. motions don't make sense in the ediff control buffer). A more complete solution would be to add even more states, which would be even more convoluted. I think using normal state as the default state everywhere and just rebinding keys to `ignore` where it makes sense is a simpler solution.

**Comment by Ambrevar** [comment]
Let's merge (and change to normal state later)?

**Comment by justbur** [comment]
I just made the change to normal state and rebased

**Comment by Ambrevar** [comment]
Thanks!

**Comment by justbur** [comment]
@bling `q` quits for me. I can't reproduce what you're seeing

**Comment by bling** [comment]
@justbur mystery solved.  i also had the old `evil-ediff` package loaded.  thanks.

**Pull request merged**
