### PR TITLE
mu4e: update mu4e-main Maildirs section

### PR DESCRIPTION
**Pull request by chinmayanagpal**
Tagging @tshu-w 

Sorry for the mess earlier. I have confirmed that this works with mu4e-maildir-shortcuts set to various values as well as unset.

### CODE REVIEW

**Comment by tshu-w** [comment]
Nice job! but there is still a tiny problem, as in the screenshot, the color of the Misc section disappeared.
Screen Shot 2022-08-08 at 12 57 57

**Comment by chinmayanagpal** [comment]
> Nice job! but there is still a tiny problem, as in the screenshot, the
> color of the Misc section disappeared.

Should be fixed now

**Comment by chinmayanagpal** [comment]
image
(nevermind)

**Comment by tshu-w** [comment]
> Nice job! but there is still a tiny problem, as in the screenshot, the color of the Misc section disappeared.
> Should be fixed now

Works fine now.

**Comment by condy0919** [comment]
@tshu-w Is it ready to merge?

**Comment by tshu-w** [comment]
> @tshu-w Is it ready to merge?

I think so.

**Pull request merged**
