### PR TITLE
Add zmusic

### PR DESCRIPTION
**Pull request by ccao001**
See #376 

https://hg.sr.ht/~zck/zmusic

### CODE REVIEW

**Comment by ccao001** [comment]
Hmmm, I thought I had squashed all previous commits till commit ```d699ad87b1d65704176f15e498cffd20f90224bb``` "Add zmusic". 

Should I clean that up somehow?

**Comment by Ambrevar** [comment]
org-present is now on master.  You can rebase your changes on master, so that the pull request only features the zmusic commits.
Let me know if you need more help.

**Comment by ccao001** [comment]
> org-present is now on master. You can rebase your changes on master, so that the pull request only features the zmusic commits.
> Let me know if you need more help.

@Ambrevar  I will be able to continue working on this PR in a few days. I will try your suggestion soon.

Thank you! :)

**Comment by ccao001** [comment]
I rebased my commit, thanks.

Sorry for the delay.

**Comment by Ambrevar** [comment]
No problem, thanks!

**Pull request merged**
