### PR TITLE
Bind evil-mc-cursors-map to `g.`

### PR DESCRIPTION
**Pull request by Silex**
😄 

Feel free to comment about `g.`

I considered `gc` or `gb` but it's taken in other modes.

### CODE REVIEW

**Comment by condy0919** [comment]
```
modes/evil-mc/evil-collection-evil-mc.el:40:11:Error: reference to free variable ‘evil-mc-key-map’
```

**Comment by Silex** [comment]
@condy0919: thanks, will fix

Also I noticed I lack the following bindings:

``` elisp
                      (kbd "M-n") 'evil-mc-make-and-goto-next-cursor
                      (kbd "M-p") 'evil-mc-make-and-goto-prev-cursor
                      (kbd "C-n") 'evil-mc-make-and-goto-next-match
                      (kbd "C-t") 'evil-mc-skip-and-goto-next-match
                      (kbd "C-p") 'evil-mc-make-and-goto-prev-match)
```

I thought they would be included in the submap but no, I'll make a new one according to personal taste and you can give feedback 😉

**Comment by condy0919** [comment]
```
modes/evil-mc/evil-collection-evil-mc.el:42:76: Error: reference to free variable ‘evil-mc-cursors-map’
```

Is `evil-mc-cursors-map` a command defined with `define-prefix-command`? If so, quote it with `'`

**Comment by Silex** [comment]
> Is `evil-mc-cursors-map` a command defined with `define-prefix-command`? If so, quote it with `'`

No it's a submap. I added a defvar for it.

Given it's a submap I'm not sure if `(defconst evil-collection-evil-mc-maps '(evil-mc-key-map evil-mc-cursors-map))` is right, what's the purpose of `evil-collection-evil-mc-maps`?

**Comment by Silex** [comment]
Ok I have set a new map, I tried to be logical reguarding how vim works.

The "FIXME" commit will be removed except if you find a way to make it work. I wanted to avoid repeating all the `(define-key..`.

**Comment by Silex** [comment]
Also maybe

``` elisp
    (kbd "0") 'evil-mc-make-and-goto-first-cursor
    (kbd "$") 'evil-mc-make-and-goto-last-cursor
```

Would be more logical as `gg`/`G` ?

**Comment by Silex** [comment]
Hum, trying `g.C-S-U` makes my emacs freeze. Do you also have that? It also happens when I try `C-h k C-S-U` (control-shift-U).

**Comment by condy0919** [comment]
> what's the purpose of `evil-collection-evil-mc-maps`?

https://github.com/emacs-evil/evil-collection/blob/master/evil-collection.el#L708

It's passed to hook function.

**Comment by condy0919** [comment]
> Hum, trying `g.C-S-U` makes my emacs freeze. Do you also have that? It also happens when I try `C-h k C-S-U` (control-shift-U).

It's identical to `C-U` or `C-S-u`

**Comment by Silex** [comment]
> It's identical to `C-U` or `C-S-u`

Well, in my emacs `(kbd "C-u")` and `(kbd "C-U")` are equivalent. But `(kbd "M-n")` and `(kbd "M-N")` are not.

**Comment by Silex** [comment]
Aynway, I couldn't find a way to rewrite it using `evil-collection-define-key` so you can merge this.

**Comment by condy0919** [comment]
@jojojames Any advices on key bindings?

**Comment by Silex** [comment]
About bindings, the only one I'm not fully happy is:

``` elisp
    (kbd "0") 'evil-mc-make-and-goto-first-cursor
    (kbd "$") 'evil-mc-make-and-goto-last-cursor
```

Which could be more logical as `g.gg` / `g.G` , but 0/$ is probably more convenient.

**Comment by jojojames** [comment]
> @jojojames Any advices on key bindings?

Nope.

**Comment by condy0919** [comment]
Merged.

**Comment by hraban** [comment]
I tried it out and it works great thanks y'all. Very excited for this. And the `g . C-h` works great, too, for a summary of what you can do with this mode.

**Pull request merged**
